package com.clock.wallpaper;
import android.app.*;import android.app.admin.DevicePolicyManager;import android.content.*;import android.hardware.*;import android.os.*;import android.provider.Settings;import java.util.*;
public class ClockService extends Service implements SensorEventListener {
 static final int FLIP_COOLDOWN=8000;
 // Пороги переворота экраном вниз (ось Z, м/с²): срабатывание при ≤ -8.6 (~30° от горизонтали), сброс при > -7.0; удержание 500 мс, без тряски
 static final float FLIP_ON=-8.6f,FLIP_OFF=-7.0f;static final int FLIP_HOLD=500;
 // Метки времени (elapsedRealtime) для согласования с WakeActivity
 static volatile long ownWakeUntil=0,lastPlug=0,lastScreenOn=0,blockedUntil=0;
 SensorManager sm;Sensor accel,prox;boolean near=false,upside=false,faceDown=false,wasUpside=false,wasFaceDown=false,showing=false,gzInit=false,flipFired=true;float gz=0;long lastWake=0,faceDownSince=0;PowerManager.WakeLock wakeLock;SharedPreferences sp;DevicePolicyManager dpm;ComponentName admin;Handler handler=new Handler(Looper.getMainLooper());BroadcastReceiver doneReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){done();}};
 // Включение экрана и подключение/отключение зарядки
 BroadcastReceiver plugReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){String a=i.getAction();long now=SystemClock.elapsedRealtime();if(Intent.ACTION_SCREEN_ON.equals(a)){lastScreenOn=now;handler.postDelayed(()->vibrateOnUserWake(0),250);}else if(Intent.ACTION_POWER_CONNECTED.equals(a)||Intent.ACTION_POWER_DISCONNECTED.equals(a))lastPlug=now;else return;maybeBlockPlugWake();handler.postDelayed(()->maybeBlockPlugWake(),700);}};
 public static void start(Context c){if(!c.getSharedPreferences("clock",0).getBoolean("clockEnabled",true))return;start(c,new Intent(c,ClockService.class));}public static void start(Context c,Intent i){if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
 @Override public void onCreate(){super.onCreate();sp=getSharedPreferences("clock",0);if(!sp.getBoolean("clockEnabled",true)){stopSelf();return;}dpm=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);admin=new ComponentName(this,ClockAdminReceiver.class);registerReceiver(doneReceiver,new IntentFilter("com.clock.wallpaper.WAKE_DONE"));IntentFilter pf=new IntentFilter(Intent.ACTION_SCREEN_ON);pf.addAction(Intent.ACTION_POWER_CONNECTED);pf.addAction(Intent.ACTION_POWER_DISCONNECTED);registerReceiver(plugReceiver,pf);sm=(SensorManager)getSystemService(SENSOR_SERVICE);accel=sm.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);prox=sm.getDefaultSensor(Sensor.TYPE_PROXIMITY);sp.edit().putBoolean("accelerometerAvailable",accel!=null).putBoolean("proximityAvailable",prox!=null).apply();if(accel!=null)sm.registerListener(this,accel,SensorManager.SENSOR_DELAY_NORMAL);if(prox!=null)sm.registerListener(this,prox,SensorManager.SENSOR_DELAY_NORMAL);if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel("clock","Clock",NotificationManager.IMPORTANCE_HIGH);getSystemService(NotificationManager.class).createNotificationChannel(ch);startForeground(7,new Notification.Builder(this,"clock").setContentTitle("Clock wallpaper active").setSmallIcon(R.drawable.ic_clock).build());}scheduleExact();}
 void scheduleExact(){Calendar n=Calendar.getInstance();n.set(Calendar.SECOND,0);n.set(Calendar.MILLISECOND,0);int next=((n.get(Calendar.MINUTE)/5)+1)*5;if(next>=60){n.add(Calendar.HOUR_OF_DAY,1);next=0;}n.set(Calendar.MINUTE,next);long at=n.getTimeInMillis();sp.edit().putLong("nextWake",at).apply();Intent i=new Intent(this,AlarmReceiver.class);PendingIntent pi=PendingIntent.getBroadcast(this,77,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);((AlarmManager)getSystemService(ALARM_SERVICE)).setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);}
 void buzz(int ms){Vibrator v=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(v!=null&&v.hasVibrator()){if(Build.VERSION.SDK_INT>=26)v.vibrate(VibrationEffect.createOneShot(ms,VibrationEffect.DEFAULT_AMPLITUDE));else v.vibrate(ms);}}
 // Виброотклик только при включении экрана пользователем: не на таймерных пробуждениях и не при погашенном зарядкой экране (такая же длина, как у виброотклика при перевороте)
 void vibrateOnUserWake(int attempt){long now=SystemClock.elapsedRealtime();if(!prefs("vibrateOnWake",true))return;if(now<ownWakeUntil||now<blockedUntil)return;if(!((PowerManager)getSystemService(POWER_SERVICE)).isInteractive())return;boolean plugRecent=lastPlug!=0&&now-lastPlug<3000&&prefs("plugProximity",true);if(plugRecent&&attempt<1){handler.postDelayed(()->vibrateOnUserWake(1),900);return;}buzz(120);}
 // Если экран включился из-за подключения/отключения зарядки — сразу гасим его обратно (независимо от датчика приближения)
 void maybeBlockPlugWake(){long now=SystemClock.elapsedRealtime();if(lastPlug==0||lastScreenOn==0)return;if(Math.abs(lastPlug-lastScreenOn)>3000||now-Math.max(lastPlug,lastScreenOn)>3000)return;if(!prefs("plugProximity",true)||now<ownWakeUntil)return;if(!((PowerManager)getSystemService(POWER_SERVICE)).isInteractive())return;lastPlug=0;lastScreenOn=0;blockedUntil=now+3000;note("Пропуск: экран включился от зарядки");if(dpm.isAdminActive(admin))dpm.lockNow();}
 void wake(String why){long now=SystemClock.elapsedRealtime();boolean flip=why.equals("flip");if(!prefs("enabled",true)){note("Отключено");return;}if(showing){note("Пропуск: уже показывается");return;}if(flip&&now-lastWake<FLIP_COOLDOWN){note("Пропуск: защита переворота");return;}boolean wasInteractive=((PowerManager)getSystemService(POWER_SERVICE)).isInteractive();if(why.equals("timer")&&wasInteractive){note("Пропуск: экран уже включён");return;}if((near&&prefs("proximity",true)&&!flip)||(faceDown&&prefs("faceDown",true)&&!flip)){note(near?"Пропуск: приближение":"Пропуск: экран вниз");return;}if(flip)buzz(120);showing=true;lastWake=now;ownWakeUntil=now+4000;sp.edit().putLong("lastWake",System.currentTimeMillis()).putString("lastReason",why).apply();PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);wakeLock=pm.newWakeLock(PowerManager.SCREEN_BRIGHT_WAKE_LOCK|PowerManager.ACQUIRE_CAUSES_WAKEUP|PowerManager.ON_AFTER_RELEASE,"ClockWallpaper:Wake");wakeLock.acquire(1500);Intent i=new Intent(this,WakeActivity.class).putExtra("screenWasOn",wasInteractive).putExtra("reason",why).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);if(Build.VERSION.SDK_INT<23||Settings.canDrawOverlays(this))startActivity(i);else{PendingIntent pi=PendingIntent.getActivity(this,42,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder nb=new Notification.Builder(this,"clock");nb.setSmallIcon(R.drawable.ic_clock).setContentTitle("Clock").setContentText("Включите показ поверх приложений").setFullScreenIntent(pi,true);getSystemService(NotificationManager.class).notify(42,nb.build());}}
 void note(String s){sp.edit().putString("lastReason",s).putLong("lastEvent",System.currentTimeMillis()).apply();}void done(){showing=false;if(wakeLock!=null&&wakeLock.isHeld()){wakeLock.release();wakeLock=null;}}
 boolean prefs(String k,boolean d){return sp.getBoolean(k,d);}
 @Override public void onSensorChanged(SensorEvent e){if(sp!=null&&!sp.getBoolean("clockEnabled",true))return;if(e.sensor.getType()==Sensor.TYPE_PROXIMITY){near=e.values[0]<e.sensor.getMaximumRange();sp.edit().putBoolean("near",near).apply();}if(e.sensor.getType()==Sensor.TYPE_ACCELEROMETER){float x=e.values[0],y=e.values[1],z=e.values[2];if(!gzInit){gz=z;gzInit=true;}else gz=gz*0.7f+z*0.3f;float mag=(float)Math.sqrt(x*x+y*y+z*z);boolean steady=mag>8.3f&&mag<11.3f;wasUpside=upside;upside=y<-7.5f;wasFaceDown=faceDown;faceDown=faceDown?gz<FLIP_OFF:gz<FLIP_ON;sp.edit().putBoolean("upside",upside).putBoolean("faceDownState",faceDown).apply();long now=SystemClock.elapsedRealtime();boolean interactive=((PowerManager)getSystemService(POWER_SERVICE)).isInteractive();if(!faceDown){flipFired=false;faceDownSince=0;}else if(!interactive){flipFired=true;faceDownSince=0;}else if(steady){if(faceDownSince==0)faceDownSince=now;if(!flipFired&&now-faceDownSince>=FLIP_HOLD&&prefs("flip",true)){flipFired=true;wake("flip");}}else faceDownSince=0;}}
 @Override public void onAccuracyChanged(Sensor s,int accuracy){}
 @Override public int onStartCommand(Intent i,int f,int id){if(sp!=null&&!sp.getBoolean("clockEnabled",true)){stopSelf();return START_NOT_STICKY;}if(i!=null&&"com.clock.wallpaper.TIMER".equals(i.getAction())){wake("timer");scheduleExact();}return START_STICKY;}@Override public void onDestroy(){unregisterReceiver(doneReceiver);try{unregisterReceiver(plugReceiver);}catch(Exception ignored){}sm.unregisterListener(this);done();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
