package com.clock.wallpaper;
import android.app.*;import android.content.*;import android.hardware.*;import android.os.*;import android.provider.Settings;import java.util.*;
public class ClockService extends Service implements SensorEventListener {
 static final int FLIP_COOLDOWN=8000;SensorManager sm;Sensor accel,prox;boolean near=false,upside=false,faceDown=false,wasUpside=false,showing=false;long lastWake=0;PowerManager.WakeLock wakeLock;SharedPreferences sp;BroadcastReceiver doneReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){done();}};
 public static void start(Context c){start(c,new Intent(c,ClockService.class));}public static void start(Context c,Intent i){if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
 @Override public void onCreate(){super.onCreate();sp=getSharedPreferences("clock",0);registerReceiver(doneReceiver,new IntentFilter("com.clock.wallpaper.WAKE_DONE"));sm=(SensorManager)getSystemService(SENSOR_SERVICE);accel=sm.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);prox=sm.getDefaultSensor(Sensor.TYPE_PROXIMITY);sp.edit().putBoolean("accelerometerAvailable",accel!=null).putBoolean("proximityAvailable",prox!=null).apply();if(accel!=null)sm.registerListener(this,accel,SensorManager.SENSOR_DELAY_NORMAL);if(prox!=null)sm.registerListener(this,prox,SensorManager.SENSOR_DELAY_NORMAL);if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel("clock","Clock",NotificationManager.IMPORTANCE_HIGH);getSystemService(NotificationManager.class).createNotificationChannel(ch);startForeground(7,new Notification.Builder(this,"clock").setContentTitle("Clock wallpaper active").setSmallIcon(R.drawable.ic_clock).build());}scheduleExact();}
 void scheduleExact(){Calendar n=Calendar.getInstance();n.set(Calendar.SECOND,0);n.set(Calendar.MILLISECOND,0);int next=((n.get(Calendar.MINUTE)/5)+1)*5;if(next>=60){n.add(Calendar.HOUR_OF_DAY,1);next=0;}n.set(Calendar.MINUTE,next);long at=n.getTimeInMillis();sp.edit().putLong("nextWake",at).apply();Intent i=new Intent(this,AlarmReceiver.class);PendingIntent pi=PendingIntent.getBroadcast(this,77,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);((AlarmManager)getSystemService(ALARM_SERVICE)).setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);}
 void wake(String why){long now=SystemClock.elapsedRealtime();if(!prefs("enabled",true)){note("Отключено");return;}if(showing){note("Пропуск: уже показывается");return;}if(why.equals("flip")&&now-lastWake<FLIP_COOLDOWN){note("Пропуск: защита переворота");return;}boolean wasInteractive=((PowerManager)getSystemService(POWER_SERVICE)).isInteractive();if(why.equals("timer")&&wasInteractive){note("Пропуск: экран уже включён");return;}if((near&&prefs("proximity",true))||(faceDown&&prefs("faceDown",true)&&!why.equals("flip"))){note(near?"Пропуск: приближение":"Пропуск: экран вниз");return;}if(why.equals("flip")){Vibrator v=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(v!=null&&v.hasVibrator()){if(Build.VERSION.SDK_INT>=26)v.vibrate(VibrationEffect.createOneShot(120,VibrationEffect.DEFAULT_AMPLITUDE));else v.vibrate(120);}}showing=true;lastWake=now;sp.edit().putLong("lastWake",System.currentTimeMillis()).putString("lastReason",why).apply();PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);wakeLock=pm.newWakeLock(PowerManager.SCREEN_BRIGHT_WAKE_LOCK|PowerManager.ACQUIRE_CAUSES_WAKEUP|PowerManager.ON_AFTER_RELEASE,"ClockWallpaper:Wake");wakeLock.acquire(1500);Intent i=new Intent(this,WakeActivity.class).putExtra("screenWasOn",wasInteractive).putExtra("reason",why).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);if(Build.VERSION.SDK_INT<23||Settings.canDrawOverlays(this))startActivity(i);else{PendingIntent pi=PendingIntent.getActivity(this,42,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder nb=new Notification.Builder(this,"clock");nb.setSmallIcon(R.drawable.ic_clock).setContentTitle("Clock").setContentText("Включите показ поверх приложений").setFullScreenIntent(pi,true);getSystemService(NotificationManager.class).notify(42,nb.build());}}
 void note(String s){sp.edit().putString("lastReason",s).putLong("lastEvent",System.currentTimeMillis()).apply();}void done(){showing=false;if(wakeLock!=null&&wakeLock.isHeld()){wakeLock.release();wakeLock=null;}}
 boolean prefs(String k,boolean d){return sp.getBoolean(k,d);}
 @Override public void onSensorChanged(SensorEvent e){if(e.sensor.getType()==Sensor.TYPE_PROXIMITY){near=e.values[0]<e.sensor.getMaximumRange();sp.edit().putBoolean("near",near).apply();}if(e.sensor.getType()==Sensor.TYPE_ACCELEROMETER){float y=e.values[1],z=e.values[2];wasUpside=upside;upside=y<-7.5f;faceDown=z<-7.5f;sp.edit().putBoolean("upside",upside).putBoolean("faceDownState",faceDown).apply();boolean interactive=((PowerManager)getSystemService(POWER_SERVICE)).isInteractive();if(interactive&&!wasUpside&&upside&&prefs("flip",true))wake("flip");}}
 @Override public void onAccuracyChanged(Sensor s,int accuracy){}
 @Override public int onStartCommand(Intent i,int f,int id){if(i!=null&&"com.clock.wallpaper.TIMER".equals(i.getAction())){wake("timer");scheduleExact();}return START_STICKY;}@Override public void onDestroy(){unregisterReceiver(doneReceiver);sm.unregisterListener(this);done();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
