package com.clock.wallpaper;

import android.app.*;import android.app.admin.DevicePolicyManager;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
 static final String PREF="clock"; DevicePolicyManager dpm; ComponentName admin; TextView diag; Handler handler=new Handler(Looper.getMainLooper());
 @Override public void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},9);dpm=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);admin=new ComponentName(this,ClockAdminReceiver.class);ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(24,24,24,20);
  TextView title=new TextView(this);title.setText("⚙  Clock Wallpaper\n   Bigme HiBreak");title.setTextSize(23);title.setTextColor(0xffffd76b);box.addView(title);TextView info=new TextView(this);info.setText("Экран обновляется по таймеру только в выключенном состоянии. Переворот запускает заставку.");info.setTextColor(0xffd8c8b0);info.setPadding(0,12,0,8);box.addView(info);
  diag=new TextView(this);diag.setTextSize(14);diag.setTextColor(0xffc9b99f);diag.setPadding(0,6,0,12);box.addView(diag);
  addSwitch(box,"⏱ Автопробуждение","enabled",true);addSwitch(box,"↕ Переворот вверх ногами","flip",true);addSwitch(box,"⌂ Домашний экран после загрузки","bootHome",true);addSwitch(box,"⌁ После перезагрузки запустить Clock","boot",true);addSwitch(box,"◉ Не включать рядом с объектом","proximity",true);addSwitch(box,"▾ Не включать экраном вниз","faceDown",true);addSwitch(box,"↺ Перевёрнутая заставка","wallpaperUpsideDown",false);
  Button alarm=new Button(this);alarm.setText("♫  Будильник: возобновить плеер");alarm.setOnClickListener(v->pickAlarm());box.addView(alarm);addSwitch(box,"Включить будильник плеера","musicAlarm",false);
  Button adminButton=new Button(this);adminButton.setText(dpm.isAdminActive(admin)?"✓ Выключение экрана разрешено":"Разрешить выключение экрана");adminButton.setOnClickListener(v->{Intent i=new Intent(DevicePolicyManager.ACTION_ADD_DEVICE_ADMIN);i.putExtra(DevicePolicyManager.EXTRA_DEVICE_ADMIN,admin);i.putExtra(DevicePolicyManager.EXTRA_ADD_EXPLANATION,"Только для выключения экрана после заставки.");startActivityForResult(i,42);});box.addView(adminButton);
  Button test=new Button(this);test.setText("▶  Показать заставку сейчас");test.setOnClickListener(v->{ClockService.start(this);startActivity(new Intent(this,WakeActivity.class).putExtra("reason","test").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP));});box.addView(test);addSwitch(box,"↻ Всегда нормальная ориентация","normalOrientation",false);
  Button start=new Button(this);start.setText("●  Запустить службу");start.setOnClickListener(v->ClockService.start(this));box.addView(start);scroll.addView(box);setContentView(scroll);ClockService.start(this);handler.post(update);
 }
 void pickAlarm(){Calendar n=Calendar.getInstance();TimePickerDialog d=new TimePickerDialog(this,(v,h,m)->{getSharedPreferences(PREF,0).edit().putInt("alarmHour",h).putInt("alarmMinute",m).putBoolean("musicAlarm",true).apply();scheduleMusicAlarm(h,m);},getSharedPreferences(PREF,0).getInt("alarmHour",8),getSharedPreferences(PREF,0).getInt("alarmMinute",0),true);d.setTitle("Время будильника");d.show();}
 void scheduleMusicAlarm(int h,int m){Calendar at=Calendar.getInstance();at.set(Calendar.HOUR_OF_DAY,h);at.set(Calendar.MINUTE,m);at.set(Calendar.SECOND,0);at.set(Calendar.MILLISECOND,0);if(at.getTimeInMillis()<=System.currentTimeMillis())at.add(Calendar.DAY_OF_YEAR,1);Intent i=new Intent(this,MusicAlarmReceiver.class);PendingIntent pi=PendingIntent.getBroadcast(this,88,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);((AlarmManager)getSystemService(ALARM_SERVICE)).setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at.getTimeInMillis(),pi);}
 Runnable update=new Runnable(){public void run(){SharedPreferences p=getSharedPreferences(PREF,0);diag.setText("Служба активна  •  следующий показ: "+fmt(p.getLong("nextWake",0))+"\nПоследний: "+fmt(p.getLong("lastWake",0))+"  •  "+p.getString("lastReason","—")+"\nДатчики: акселерометр "+(p.getBoolean("accelerometerAvailable",false)?"✓":"—")+"  приближение "+(p.getBoolean("proximityAvailable",false)?"✓":"—"));handler.postDelayed(this,1000);}};
 String fmt(long t){return t==0?"—":new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date(t));}
 void addSwitch(LinearLayout box,String label,String key,boolean def){Switch s=new Switch(this);s.setText(label);s.setTextColor(0xfff0dfc0);s.setChecked(getSharedPreferences(PREF,0).getBoolean(key,def));s.setOnCheckedChangeListener((v,c)->{getSharedPreferences(PREF,0).edit().putBoolean(key,c).apply();if(key.equals("musicAlarm")&&c)scheduleMusicAlarm(getSharedPreferences(PREF,0).getInt("alarmHour",8),getSharedPreferences(PREF,0).getInt("alarmMinute",0));});box.addView(s);}
 @Override protected void onDestroy(){handler.removeCallbacks(update);super.onDestroy();}
}
