package com.clock.wallpaper;

import android.app.*;import android.app.admin.DevicePolicyManager;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
  static final String PREF="clock"; DevicePolicyManager dpm; ComponentName admin; TextView diag; Handler handler=new Handler(Looper.getMainLooper());
  @Override public void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},9);dpm=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);admin=new ComponentName(this,ClockAdminReceiver.class);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(32,32,32,24);
    TextView title=new TextView(this);title.setText("Clock Wallpaper\nBigme HiBreak");title.setTextSize(24);box.addView(title);TextView info=new TextView(this);info.setText("Часы обновляются каждые 5 минут. Ниже видно, работает ли таймер и датчики.");info.setPadding(0,18,0,10);box.addView(info);
    diag=new TextView(this);diag.setTextSize(15);diag.setPadding(0,8,0,16);box.addView(diag);
    addSwitch(box,"Включить автоматическое пробуждение","enabled",true);addSwitch(box,"Включать при перевороте портретом вверх ногами","flip",true);addSwitch(box,"Не включать при датчике приближения","proximity",true);addSwitch(box,"Не включать, если телефон лежит экраном вниз","faceDown",true);addSwitch(box,"Работать после перезагрузки","boot",true);addSwitch(box,"Показывать заставку вверх ногами","wallpaperUpsideDown",false);
    Button overlayButton=new Button(this);overlayButton.setText("Разрешить автоматическую заставку поверх приложений");overlayButton.setOnClickListener(v->{if(Build.VERSION.SDK_INT>=23)startActivity(new Intent(android.provider.Settings.ACTION_MANAGE_OVERLAY_PERMISSION,android.net.Uri.parse("package:"+getPackageName())));});box.addView(overlayButton);
    Button adminButton=new Button(this);adminButton.setText(dpm.isAdminActive(admin)?"Выключение экрана разрешено":"Разрешить автоматическое выключение экрана (необязательно)");adminButton.setOnClickListener(v->{Intent i=new Intent(DevicePolicyManager.ACTION_ADD_DEVICE_ADMIN);i.putExtra(DevicePolicyManager.EXTRA_DEVICE_ADMIN,admin);i.putExtra(DevicePolicyManager.EXTRA_ADD_EXPLANATION,"Только для выключения экрана после заставки. PIN или пароль не включается.");startActivityForResult(i,42);});box.addView(adminButton);
    Button start=new Button(this);start.setText("Запустить службу сейчас");start.setOnClickListener(v->ClockService.start(this));box.addView(start);setContentView(box);ClockService.start(this);handler.post(update);
  }
  Runnable update=new Runnable(){public void run(){SharedPreferences p=getSharedPreferences(PREF,0);diag.setText("Состояние службы: активно\nПоследний показ: "+fmt(p.getLong("lastWake",0))+"\nСледующий показ: "+fmt(p.getLong("nextWake",0))+"\nПричина/результат: "+p.getString("lastReason","ещё не было")+"\nАкселерометр: "+(p.getBoolean("accelerometerAvailable",false)?"есть":"нет")+" | Перевёрнут: "+yes(p.getBoolean("upside",false))+" | Экран вниз: "+yes(p.getBoolean("faceDownState",false))+"\nПриближение: "+(p.getBoolean("proximityAvailable",false)?"есть":"нет")+" | Закрыт: "+yes(p.getBoolean("near",false)));handler.postDelayed(this,1000);}};
  String yes(boolean b){return b?"да":"нет";}String fmt(long t){return t==0?"—":new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date(t));}
  void addSwitch(LinearLayout box,String label,String key,boolean def){Switch s=new Switch(this);s.setText(label);s.setChecked(getSharedPreferences(PREF,0).getBoolean(key,def));s.setOnCheckedChangeListener((v,c)->getSharedPreferences(PREF,0).edit().putBoolean(key,c).apply());box.addView(s);}
  @Override protected void onDestroy(){handler.removeCallbacks(update);super.onDestroy();}
}
