package com.clock.wallpaper;

import android.content.*;import android.graphics.*;import android.view.*;import java.util.*;

public class ScreenHandsOverlay extends View {
  Paint p=new Paint(3); Calendar now=Calendar.getInstance(); boolean upside; int battery=100; boolean charging=false; String chargeType="";
  ScreenHandsOverlay(Context c,boolean u){super(c);upside=u;p.setStrokeCap(Paint.Cap.ROUND);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
  void hand(Canvas c,float cx,float cy,float len,float angle,float width,int color){double a=Math.toRadians(angle-90);float x=cx+(float)Math.cos(a)*len,y=cy+(float)Math.sin(a)*len;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(width+10);p.setColor(Color.argb(190,20,5,0));c.drawLine(cx,cy,x,y,p);p.setStrokeWidth(width);p.setColor(color);c.drawLine(cx,cy,x,y,p);p.setStyle(Paint.Style.FILL);p.setColor(color);c.drawCircle(x,y,width*1.25f,p);}
  void handLabel(Canvas c,float cx,float cy,float len,float angle,float width,int color,String label){hand(c,cx,cy,len,angle,width,color);double a=Math.toRadians(angle-90);float x=cx+(float)Math.cos(a)*len,y=cy+(float)Math.sin(a)*len;float r=Math.max(22,width*3.01f);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(70,22,4));c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);p.setColor(color);c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(Math.max(18,width*1.75f));p.setColor(color);p.setShadowLayer(4,1,1,Color.BLACK);c.drawText(label,x,y-p.ascent()/2-p.descent()/2,p);p.clearShadowLayer();}
  @Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),cx=w*.53f,cy=h*.46f;now=Calendar.getInstance();int gold=Color.rgb(255,218,86),light=Color.rgb(255,240,150);float hour=((now.get(Calendar.HOUR_OF_DAY)%12)+now.get(Calendar.MINUTE)/60f)/12f*360f;float minute=(now.get(Calendar.MINUTE)+now.get(Calendar.SECOND)/60f)/60f*360f;hand(c,cx,cy,Math.min(w,h)*.27f,hour,Math.max(15,w*.027f),gold);hand(c,cx,cy,Math.min(w,h)*.45f,minute,Math.max(11,w*.018f),light);
    float wx=w*.271f,wy=h*.464f;float week=((now.get(Calendar.DAY_OF_WEEK)-1)/7f)*360f;hand(c,wx,wy,Math.min(w,h)*.10725f,week,Math.max(10,w*.018f),Color.rgb(255,225,105));
    float topX=w*.5f,topY=h*.218f;float batteryAngle=360f-(battery/100f)*360f;hand(c,topX,topY,Math.min(w,h)*.1725f,batteryAngle,Math.max(7,w*.0135f),gold);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(Math.max(13,w*.028f));p.setColor(gold);p.setShadowLayer(4,1,1,Color.BLACK);c.drawText(battery+"%"+(charging?"  "+chargeType:""),topX,h*.285f,p);p.clearShadowLayer();
    float bottomY=h*.72f;float month=now.get(Calendar.MONTH)/12f*360f;float day=(now.get(Calendar.DAY_OF_MONTH)-1)/31f*360f;handLabel(c,cx-w*.03f,bottomY,Math.min(w,h)*.115f,month,Math.max(5,w*.009f),gold,String.valueOf(now.get(Calendar.MONTH)+1));handLabel(c,cx-w*.03f,bottomY,Math.min(w,h)*.155f,day,Math.max(5,w*.009f),light,String.valueOf(now.get(Calendar.DAY_OF_MONTH)));
    p.setStyle(Paint.Style.FILL);p.setColor(gold);c.drawCircle(cx,cy,Math.max(12,w*.022f),p);p.setColor(Color.rgb(75,20,4));c.drawCircle(cx,cy,Math.max(5,w*.010f),p);}
  public void setBattery(int value,boolean isCharging,String type){battery=Math.max(0,Math.min(100,value));charging=isCharging;chargeType=type==null?"":type;invalidate();}
}
