package com.clock.wallpaper;

import android.app.*;import android.app.admin.DevicePolicyManager;import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class WakeActivity extends Activity {
  DevicePolicyManager dpm;ComponentName admin;Handler handler=new Handler(Looper.getMainLooper());Runnable lockTask,clockTask;TextView live;
  @Override public void onCreate(Bundle b){super.onCreate(b);dpm=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);admin=new ComponentName(this,ClockAdminReceiver.class);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON|WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);FrameLayout frame=new FrameLayout(this);ImageView image=new ImageView(this);image.setImageResource(R.drawable.clock_wallpaper);image.setScaleType(ImageView.ScaleType.FIT_XY);if(getSharedPreferences("clock",0).getBoolean("wallpaperUpsideDown",false))image.setRotation(180);frame.addView(image);live=new TextView(this);live.setTextColor(Color.rgb(255,225,120));live.setTextSize(30);live.setTypeface(Typeface.DEFAULT,Typeface.BOLD);live.setGravity(Gravity.CENTER);live.setShadowLayer(5,2,2,Color.BLACK);FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(-1,90,Gravity.BOTTOM);lp.setMargins(0,0,0,34);frame.addView(live,lp);image.setOnClickListener(v->{cancelLock();startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));finish();});setContentView(frame);clockTask=()->{live.setText(new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date()));handler.postDelayed(clockTask,1000);};handler.post(clockTask);scheduleLock();}
  @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);scheduleLock();}
  void scheduleLock(){if(lockTask!=null)handler.removeCallbacks(lockTask);lockTask=()->{sendBroadcast(new Intent("com.clock.wallpaper.WAKE_DONE"));if(dpm.isAdminActive(admin))dpm.lockNow();else finishAndRemoveTask();};handler.postDelayed(lockTask,1000);}
  void cancelLock(){if(lockTask!=null)handler.removeCallbacks(lockTask);sendBroadcast(new Intent("com.clock.wallpaper.WAKE_DONE"));}
  @Override public void onBackPressed(){cancelLock();finish();}
  @Override protected void onDestroy(){if(lockTask!=null)handler.removeCallbacks(lockTask);if(clockTask!=null)handler.removeCallbacks(clockTask);sendBroadcast(new Intent("com.clock.wallpaper.WAKE_DONE"));super.onDestroy();}
}
